### ISSUE TITLE
Merging two level object deletes part.

### ISSUE THREAD

**Issue by TimMeade** [yeikos/js.merge#22]
Two objects:
var one = {
      meta : {
          source:"One"
      }
  }

var two = {
      meta : {
          source2:"Two"
      }
 }

var newData = merge(one, two)

and the result is: 
{
  "meta": {
    "source2": "Two"
  }
}

I would have expected: 
{
  "meta": {
    "source": "One",
    "source2": "Two"
  }
}

am i off base here?  Or using it incorrectly?

Thanks

**Comment by megastef** [comment]
````
var merge = require('merge')
var one = {
meta : {
source:"One"
}
}

var two = {
meta : {
source2:"Two"
}
}

var newData = merge.recursive(true, one, two)
console.log(newData)
```

results in:
```
{ meta: { source: 'One', source2: 'Two' } }
```

**Comment by yeikos** [comment]
Use `merge.recursive` as megastef said.
