### ISSUE TITLE
Is it really necessary? Can Object.assign() do the same thing in NodeJs?

### ISSUE THREAD

**Issue by Jeff-Tian** [yeikos/js.merge#26]
Didn't see the necessary for this repo because in NodeJs `Object.assign()` can do the same thing.

**Comment by pandapaul** [comment]
I don't think `Object.assign()` offers a recursive merge, so the `merge.recursive()` functionality is very welcome.

**Comment by Jeff-Tian** [comment]
Cool, thanks.
