### ISSUE TITLE
Prototype pollution attack (merge.recursive)

### ISSUE THREAD

**Issue by pavel-gatilov-epam** [yeikos/js.merge#27]
A Prototype pollution attack caused by merge 1.2.0 with High rank has been disclosed recently at https://hackerone.com/reports/381194

Please see if it can be fixed

**Comment by jrdev128** [comment]
Thanks for the report, fixed it.

**Comment by yeikos** [comment]
Thanks for the report, fixed it.

**Comment by yeikos** [comment]
Thanks for the report, fixed it.
